name: Deploy to PyPI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout...
        uses: actions/checkout@v4

      - name: Set up Python...
        uses: actions/setup-python@v5

      - name: Install build dependencies...
        run: pip install setuptools wheel twine

      - name: Build...
        run: pip wheel -w dist .

      - name: Upload to PyPI...
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: twine upload --repository testpypi dist/*
